### ISSUE TITLE
Annotation Excluded

### ISSUE THREAD

**Issue by mahsayedsalem** [JovanSardinha/data-science-bowl-2017#10]
Where can I download this CSV file? I can't find it anywhere

**Comment by jovsa** [comment]
@mahsayedsalem  - The data can be downloaded at the [LUNA data page](https://luna16.grand-challenge.org/data/). You will have to log in/create an account to download any data.

**Comment by mahsayedsalem** [comment]
I meant the Annotation Excluded CSV file, but it's okay I finally found it. Thanks for the great tutorials btw!
